### ISSUE TITLE
Expect this project.

### ISSUE THREAD

**Issue by komputronika** [yidas/php-pagination#1]
I expect this project.
Please share your code.
Thanks

**Comment by yidas** [comment]
Hi,

Thanks for your like.

This pagination lib would be built for pure PHP and Codeigniter 3 ([See this scenario](https://github.com/yidas/codeigniter-model/issues/4#issuecomment-419606336))

**Comment by yidas** [comment]
Hi @komputronika,

The [version 1.0.0](https://github.com/yidas/php-pagination/releases/tag/1.0.0) is released.

Cheers.
