### ISSUE TITLE
need to echo yidas\widgets\Pagination::widget() in twig template

### ISSUE THREAD

**Issue by rudolphp** [yidas/php-pagination#2]
How do I save output of yidas\widgets\Pagination::widget() in a variable in the controller so I can pass it to the template file like twig to be printed.
Thank you. this is a nice package!

**Comment by rudolphp** [comment]
the doc says we need to echo yidas\widgets\Pagination::widget(), but echo is not needed. the function prints without echo. Ideally it should work only with echo.

**Comment by yidas** [comment]
Hi @rudolphp,

Thank you for your appreciation.

You could try to assign widget output to a variable, for example:

```php
use yidas\widgets\Pagination;

$widgetHtml =  Pagination::widget([
    'pagination' => $pagination
]);
```

Cheers
