### ISSUE TITLE
Pagination $param property not used to build links in  ->createUrl() method

### ISSUE THREAD

**Issue by tamedevelopers** [yidas/php-pagination#4]
Hi Friend,

AM using your package and for now just had to copy and past code to edit fix.
Please let me know when you update the error.

For the yidas\data\Pagination

You added support for additional params
/**
     * Parameters (name => value) that should be used to obtain the current page number and to create new pagination URLs
     *
     * @var array
     */
    public $params;
    
    But never used it.
    
    ----
    So for the ->createUrl() method
    
    I manually updated a copy of the downloaded code
    
    // Build URL
    $url = "//{$_SERVER['HTTP_HOST']}{$requestUri}?" . http_build_query(array_merge($_GET, $params, $this->params));
    
    Since you used array merge to merge all arrays. Then building a custom pagination url links would be nice.
    
    Seems you forgot to add that part
    
    Fix here
    http_build_query(array_merge($_GET, $params, $this->params))

**Comment by yidas** [comment]
Hi @tamedevelopers ,

Really appreciate your help!
I've released a version with this issue handled.

Thank you
